name: Deploy build to S3 Bucket

on:
  push:
    branches:
      - master

jobs:
  Create-Production-Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Installing Dependencies
        run: yarn install
      - name: Creating Production Bundle
        run: yarn build
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-1
      - name: Deploy
        uses: jonelantha/gatsby-s3-action@v1
        with:
          dest-s3-bucket: www-ondecentral-com
          cloudfront-id-to-invalidate: E5VY5XQQ664ZA
