name: Deploy build to S3 Bucket

on:
  push:
    branches:
      - master
      - team-section

jobs:
  Create-Production-Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Installing Dependencies
        run: yarn install
      - name: Creating Production Bundle
        run: yarn build
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Deploy
        uses: jonelantha/gatsby-s3-action@v1
        with:
          dest-s3-bucket: www-stage-ondecentral-com
#    steps:
#      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
#      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
#      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
#      - name: Check out repository code
#        uses: actions/checkout@v3
#      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
#      - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."
#      - run: yarn install
#      - run: yarn build
#      - run: export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
#      - run: export AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
#      - run: yarn deploy
#      - run: echo "ğŸ This job's status is ${{ job.status }}."
